/* Generated by re2c */
#include "php_snuffleupagus.h"

enum YYCONDTYPE {
	yycinit,
	yyccond,
	yyccond_op,
	yycrule,
};


#define cs_log_error(fmt, ...) sp_log_err("config", fmt, ##__VA_ARGS__)
#define cs_log_info(fmt, ...) sp_log_msg("config", SP_LOG_INFO, fmt, ##__VA_ARGS__)
#define cs_log_warning(fmt, ...) sp_log_warn("config", fmt, ##__VA_ARGS__)


zend_string *sp_get_arg_string(sp_parsed_keyword *kw) {
  if (!kw || !kw->arg) {
    return NULL;
  }
  zend_string *ret = zend_string_init(kw->arg, kw->arglen, 1);
  char *pin, *pout;
  pin = pout = ZSTR_VAL(ret);
  char *pend = pin + ZSTR_LEN(ret);

  while (pin < pend) {
    if (*pin == '\\') {
      pin++;
    }
    *pout = *pin;
    pin++; pout++;
  }

  if (pin != pout) {
    size_t len = pout - ZSTR_VAL(ret);
    ret = zend_string_truncate(ret, len, 1);
    ZSTR_VAL(ret)[len] = 0;
  }

  return ret;
}

zend_string *sp_get_textual_representation(sp_parsed_keyword *parsed_rule) {
  // a rule is "sp.keyword...keyword(arg);\0"
  size_t len = 3; // sp + ;
  sp_parsed_keyword *kw;
  for (kw = parsed_rule; kw->kw; kw++) {
    len++; // .
    len += kw->kwlen;
    if (kw->argtype == SP_ARGTYPE_EMPTY) {
      len += 2; // ()
    } else if (kw->argtype == SP_ARGTYPE_STR) {
        len += 4;
        len += kw->arglen;
    }
  }
  zend_string *ret = zend_string_alloc(len, 1);
  char *ptr = ZSTR_VAL(ret);
  memcpy(ptr, "sp", 2); ptr += 2;
  for (kw = parsed_rule; kw->kw; kw++) {
    *ptr++ = '.';
    memcpy(ptr, kw->kw, kw->kwlen); ptr += kw->kwlen;
    if (kw->argtype == SP_ARGTYPE_EMPTY || kw->argtype == SP_ARGTYPE_STR || kw->argtype == SP_ARGTYPE_UNKNOWN) {
      *ptr++ = '(';
    }
    if (kw->argtype == SP_ARGTYPE_STR && kw->arg) {
      *ptr++ = '"';
      memcpy(ptr, kw->arg, kw->arglen); ptr += kw->arglen;
      *ptr++ = '"';
    }
    if (kw->argtype == SP_ARGTYPE_EMPTY || kw->argtype == SP_ARGTYPE_STR || kw->argtype == SP_ARGTYPE_UNKNOWN) {
      *ptr++ = ')';
    }
  }
  *ptr++ = ';';
  *ptr = 0;
  return ret;
}

static void str_dtor(zval *zv) {
  zend_string_release_ex(Z_STR_P(zv), 1);
}

// sy_ functions and macros are helpers for the shunting yard algorithm
#define sy_res_push(val) \
  if (cond_res_i >= 100) { cs_log_error("condition too complex on line %d", lineno); goto out; } \
  cond_res[cond_res_i++] = val;
#define sy_res_pop() cond_res[--cond_res_i]
#define sy_op_push(op) \
  if (cond_op_i >= 100) { cs_log_error("condition too complex on line %d", lineno); goto out; } \
  cond_op[cond_op_i++] = op;
#define sy_op_pop() cond_op[--cond_op_i]
#define sy_op_peek() cond_op[cond_op_i-1]

static inline int sy_op_precedence(char op) {
  switch (op) {
    case '!': return 120;
    case '<':
    case '>':
    case 'L': // <=
    case 'G': // >=
              return 90;
    case '&': return 70;
    case '|': return 60;
    case '=': return 20;
  }
  return 0;
}
static inline int sy_op_is_left_assoc(char op) {
  switch (op) {
    case '!': return 0;
  }
  return 1;
}
static int sy_apply_op(char op, int a, int b) {
  switch (op) {
    case '!': return !a;
    case '&': return (b && a);
    case '|': return (b || a);
    case '<': return (b < a);
    case 'L': return (b <= a);
    case 'G': return (b >= a);
    case '>': return (b > a);
    case '=': return (b == a);
  }
  return 0;
}

#define SY_APPLY_OP_FROM_STACK() \
  char op = sy_op_pop(); \
  int unary = (op == '!'); \
  if (cond_res_i < (2 - unary)) { cs_log_error("not enough input on line %d", lineno); goto out; } \
  int a = sy_res_pop(); \
  int b = unary ? 0 : sy_res_pop(); \
  int res = sy_apply_op(op, a, b); \
  sy_res_push(res);

#define TMPSTR(tmpstr, t2, t1) \
      char tmpstr[1024]; \
      size_t tmplen = MIN(t2-t1-2, 1023); \
      strncpy(tmpstr, t1+1, tmplen); \
      tmpstr[tmplen] = 0;


zend_result sp_config_scan(char *data, zend_result (*process_rule)(sp_parsed_keyword*))
{
  const char *YYCURSOR = data;
  const char *YYMARKER, *t1, *t2, *t3, *t4;
  const char *yyt1;
const char *yyt2;
const char *yyt3;
const char *yyt4;


  int ret = FAILURE;

  const int max_keywords = 16;
  sp_parsed_keyword parsed_rule[max_keywords+1];
  int kw_i = 0;

  HashTable vars;
  zend_hash_init(&vars, 10, NULL, str_dtor, 1);
  zend_hash_str_add_ptr(&vars, ZEND_STRL("PHP_VERSION_ID"), zend_string_init(ZEND_STRL(ZEND_TOSTR(PHP_VERSION_ID)), 1));


  int cond_res[100] = {1};
  int cond_res_i = 0;
  char cond_op[100] = {0};
  int cond_op_i = 0;

  int cond = yycinit;
  long lineno = 1;

  
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	if (cond < 2) {
		if (cond < 1) {
			goto yyc_init;
		} else {
			goto yyc_cond;
		}
	} else {
		if (cond < 3) {
			goto yyc_cond_op;
		} else {
			goto yyc_rule;
		}
	}
/* *********************************** */
yyc_init:
	{
		static const unsigned char yybm[] = {
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  88,   0,  80,  80,  16,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 88,  80,  16,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			112, 112, 112, 112, 112, 112, 112, 112, 
			112, 112,  80,  80,  80,  80,  80,  80, 
			 80, 112, 112, 112, 112, 112, 112, 112, 
			112, 112, 112, 112, 112, 112, 112, 112, 
			112, 112, 112, 112, 112, 112, 112, 112, 
			112, 112, 112,  80, 144,  80,  80, 112, 
			 80, 112, 112, 112, 112, 112, 112, 112, 
			112, 112, 112, 112, 112, 112, 112, 112, 
			112, 112, 112, 112, 112, 112, 112, 112, 
			112, 112, 112,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
			 80,  80,  80,  80,  80,  80,  80,  80, 
		};
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy6;
		}
		if (yych <= '#') {
			if (yych <= '\n') {
				if (yych <= 0x00) goto yy2;
				if (yych <= 0x08) goto yy4;
				goto yy9;
			} else {
				if (yych == '\r') goto yy11;
				if (yych <= '"') goto yy4;
				goto yy12;
			}
		} else {
			if (yych <= '?') {
				if (yych == ';') goto yy12;
				goto yy4;
			} else {
				if (yych <= '@') goto yy15;
				if (yych == 's') goto yy16;
				goto yy4;
			}
		}
yy2:
		++YYCURSOR;
		{ ret = SUCCESS; goto out; }
yy4:
		++YYCURSOR;
yy5:
		{ cs_log_error("Parser error on line %d", lineno); goto out; }
yy6:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy6;
		}
		{ goto yyc_init; }
yy9:
		++YYCURSOR;
		{ lineno++; goto yyc_init; }
yy11:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy9;
		goto yy5;
yy12:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 16) {
			goto yy12;
		}
		{ goto yyc_init; }
yy15:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		switch (yych) {
		case 'c':	goto yy17;
		case 'e':	goto yy19;
		case 'i':	goto yy20;
		case 'l':	goto yy21;
		case 'w':	goto yy22;
		default:	goto yy5;
		}
yy16:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == 'e') goto yy23;
		if (yych == 'p') goto yy24;
		goto yy5;
yy17:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy26;
yy18:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 4) {
			if (yyaccept <= 2) {
				if (yyaccept <= 1) {
					if (yyaccept == 0) {
						goto yy5;
					} else {
						yyt2 = YYCURSOR;
						goto yy66;
					}
				} else {
					yyt2 = YYCURSOR;
					goto yy70;
				}
			} else {
				if (yyaccept == 3) {
					goto yy66;
				} else {
					goto yy70;
				}
			}
		} else {
			if (yyaccept <= 6) {
				if (yyaccept == 5) {
					yyt2 = YYCURSOR;
					goto yy85;
				} else {
					yyt4 = YYCURSOR;
					goto yy90;
				}
			} else {
				if (yyaccept == 7) {
					goto yy85;
				} else {
					goto yy90;
				}
			}
		}
yy19:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy27;
		if (yych == 'r') goto yy28;
		goto yy18;
yy20:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy29;
		goto yy18;
yy21:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy30;
		goto yy18;
yy22:
		yych = *++YYCURSOR;
		if (yych == 'a') goto yy31;
		goto yy18;
yy23:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy32;
		goto yy18;
yy24:
		++YYCURSOR;
		{ kw_i = 0;  goto yyc_rule; }
yy26:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy33;
		goto yy18;
yy27:
		yych = *++YYCURSOR;
		if (yych == 'd') goto yy34;
		goto yy18;
yy28:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy35;
		goto yy18;
yy29:
		yych = *++YYCURSOR;
		if (yych == 'f') goto yy36;
		goto yy18;
yy30:
		yych = *++YYCURSOR;
		if (yych == 'g') goto yy37;
		goto yy18;
yy31:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy38;
		goto yy18;
yy32:
		yych = *++YYCURSOR;
		if (yych == '\t') goto yy39;
		if (yych == ' ') goto yy39;
		goto yy18;
yy33:
		yych = *++YYCURSOR;
		if (yych == 'd') goto yy41;
		goto yy18;
yy34:
		yych = *++YYCURSOR;
		if (yych == '_') goto yy42;
		goto yy18;
yy35:
		yych = *++YYCURSOR;
		if (yych == '"') goto yy18;
		if (yych == 'o') goto yy45;
		goto yy44;
yy36:
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy18;
yy37:
		yych = *++YYCURSOR;
		if (yych == '"') goto yy18;
		goto yy47;
yy38:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy48;
		goto yy18;
yy39:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '\t') {
				if (yych <= 0x08) goto yy18;
				goto yy39;
			} else {
				if (yych == ' ') goto yy39;
				goto yy18;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') {
					yyt1 = YYCURSOR;
					goto yy49;
				}
				if (yych <= '^') goto yy18;
				yyt1 = YYCURSOR;
				goto yy49;
			} else {
				if (yych <= '`') goto yy18;
				if (yych <= 'z') {
					yyt1 = YYCURSOR;
					goto yy49;
				}
				goto yy18;
			}
		}
yy41:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy51;
		goto yy18;
yy42:
		yych = *++YYCURSOR;
		if (yych == 'c') goto yy52;
		goto yy18;
yy43:
		yych = *++YYCURSOR;
yy44:
		if (yych <= 0x1F) {
			if (yych == '\t') goto yy43;
			goto yy18;
		} else {
			if (yych <= ' ') goto yy43;
			if (yych == '"') {
				yyt1 = YYCURSOR;
				goto yy53;
			}
			goto yy18;
		}
yy45:
		yych = *++YYCURSOR;
		if (yych == 'r') goto yy55;
		goto yy18;
yy46:
		yych = *++YYCURSOR;
yy47:
		if (yych <= 0x1F) {
			if (yych == '\t') goto yy46;
			goto yy18;
		} else {
			if (yych <= ' ') goto yy46;
			if (yych == '"') {
				yyt1 = YYCURSOR;
				goto yy56;
			}
			goto yy18;
		}
yy48:
		yych = *++YYCURSOR;
		if (yych == '"') goto yy18;
		if (yych == 'i') goto yy60;
		goto yy59;
yy49:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 32) {
			goto yy49;
		}
		if (yych == '\t') {
			yyt2 = YYCURSOR;
			goto yy61;
		}
		if (yych == ' ') {
			yyt2 = YYCURSOR;
			goto yy61;
		}
		goto yy18;
yy51:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy63;
		goto yy18;
yy52:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy64;
		goto yy18;
yy53:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy53;
		}
		if (yych <= '\r') goto yy18;
		if (yych <= '"') goto yy65;
		goto yy67;
yy55:
		yych = *++YYCURSOR;
		if (yych == '"') goto yy18;
		goto yy44;
yy56:
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych == '\n') goto yy18;
			if (yych <= '\f') goto yy56;
			goto yy18;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy56;
				goto yy69;
			} else {
				if (yych == '\\') goto yy71;
				goto yy56;
			}
		}
yy58:
		yych = *++YYCURSOR;
yy59:
		if (yych <= 0x1F) {
			if (yych == '\t') goto yy58;
			goto yy18;
		} else {
			if (yych <= ' ') goto yy58;
			if (yych == '"') {
				yyt1 = YYCURSOR;
				goto yy73;
			}
			goto yy18;
		}
yy60:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy75;
		goto yy18;
yy61:
		yych = *++YYCURSOR;
		if (yych <= 0x1F) {
			if (yych == '\t') goto yy61;
			goto yy18;
		} else {
			if (yych <= ' ') goto yy61;
			if (yych == '"') {
				yyt3 = YYCURSOR;
				goto yy76;
			}
			goto yy18;
		}
yy63:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy78;
		goto yy18;
yy64:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy79;
		goto yy18;
yy65:
		yych = *++YYCURSOR;
		yyt2 = YYCURSOR;
		if (yych == ';') goto yy80;
yy66:
		t1 = yyt1;
		t2 = yyt2;
		{
      if (!cond_res[0]) { goto yyc_init; }
      TMPSTR(tmpstr, t2, t1);
      cs_log_error("[line %d]: %s", lineno, tmpstr);
      goto out;
    }
yy67:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy53;
		}
		if (yych <= '\r') goto yy18;
		if (yych <= '"') goto yy81;
		goto yy67;
yy69:
		yych = *++YYCURSOR;
		yyt2 = YYCURSOR;
		if (yych == ';') goto yy82;
yy70:
		t1 = yyt1;
		t2 = yyt2;
		{
      if (!cond_res[0]) { goto yyc_init; }
      TMPSTR(tmpstr, t2, t1);
      cs_log_info("[line %d]: %s", lineno, tmpstr);
      goto yyc_init;
    }
yy71:
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych == '\n') goto yy18;
			if (yych <= '\f') goto yy56;
			goto yy18;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy56;
				goto yy83;
			} else {
				if (yych == '\\') goto yy71;
				goto yy56;
			}
		}
yy73:
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych == '\n') goto yy18;
			if (yych <= '\f') goto yy73;
			goto yy18;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy73;
				goto yy84;
			} else {
				if (yych == '\\') goto yy86;
				goto yy73;
			}
		}
yy75:
		yych = *++YYCURSOR;
		if (yych == 'g') goto yy88;
		goto yy18;
yy76:
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych == '\n') goto yy18;
			if (yych <= '\f') goto yy76;
			goto yy18;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy76;
				goto yy89;
			} else {
				if (yych == '\\') goto yy91;
				goto yy76;
			}
		}
yy78:
		yych = *++YYCURSOR;
		if (yych == 'o') goto yy93;
		goto yy18;
yy79:
		yych = *++YYCURSOR;
		if (yych == 'd') goto yy94;
		goto yy18;
yy80:
		++YYCURSOR;
		goto yy66;
yy81:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 128) {
			goto yy67;
		}
		if (yych <= '\r') {
			if (yych == '\n') {
				yyt2 = YYCURSOR;
				goto yy66;
			}
			if (yych <= '\f') goto yy53;
			yyt2 = YYCURSOR;
			goto yy66;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy53;
				goto yy65;
			} else {
				if (yych == ';') {
					yyt2 = YYCURSOR;
					goto yy95;
				}
				goto yy53;
			}
		}
yy82:
		++YYCURSOR;
		goto yy70;
yy83:
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '!') {
			if (yych <= '\n') {
				if (yych <= '\t') goto yy56;
				yyt2 = YYCURSOR;
				goto yy70;
			} else {
				if (yych == '\r') {
					yyt2 = YYCURSOR;
					goto yy70;
				}
				goto yy56;
			}
		} else {
			if (yych <= ';') {
				if (yych <= '"') goto yy69;
				if (yych <= ':') goto yy56;
				yyt2 = YYCURSOR;
				goto yy96;
			} else {
				if (yych == '\\') goto yy71;
				goto yy56;
			}
		}
yy84:
		yych = *++YYCURSOR;
		yyt2 = YYCURSOR;
		if (yych == ';') goto yy97;
yy85:
		t1 = yyt1;
		t2 = yyt2;
		{
      if (!cond_res[0]) { goto yyc_init; }
      TMPSTR(tmpstr, t2, t1);
      cs_log_warning("[line %d]: %s", lineno, tmpstr);
      goto yyc_init;
    }
yy86:
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych == '\n') goto yy18;
			if (yych <= '\f') goto yy73;
			goto yy18;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy73;
				goto yy98;
			} else {
				if (yych == '\\') goto yy86;
				goto yy73;
			}
		}
yy88:
		yych = *++YYCURSOR;
		if (yych == '"') goto yy18;
		goto yy59;
yy89:
		yych = *++YYCURSOR;
		yyt4 = YYCURSOR;
		goto yy100;
yy90:
		t1 = yyt1;
		t2 = yyt2;
		t3 = yyt3;
		t4 = yyt4;
		{
      if (!cond_res[0]) { goto yyc_init; }
      char *key = (char*)t1;
      int keylen = t2-t1;
      zend_string *tmp = zend_hash_str_find_ptr(&vars, key, keylen);
      if (tmp) {
        zend_hash_str_del(&vars, key, keylen);
      }
      tmp = zend_string_init(t3+1, t4-t3-2, 1);
      zend_hash_str_add_ptr(&vars, key, keylen, tmp);
      goto yyc_init;
    }
yy91:
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych == '\n') goto yy18;
			if (yych <= '\f') goto yy76;
			goto yy18;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy76;
				goto yy102;
			} else {
				if (yych == '\\') goto yy91;
				goto yy76;
			}
		}
yy93:
		yych = *++YYCURSOR;
		if (yych == 'n') goto yy103;
		goto yy18;
yy94:
		yych = *++YYCURSOR;
		if (yych == 'i') goto yy104;
		goto yy18;
yy95:
		yyaccept = 3;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy53;
		}
		if (yych <= '\r') goto yy66;
		if (yych <= '"') goto yy65;
		goto yy67;
yy96:
		yyaccept = 4;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '\r') {
			if (yych == '\n') goto yy70;
			if (yych <= '\f') goto yy56;
			goto yy70;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy56;
				goto yy69;
			} else {
				if (yych == '\\') goto yy71;
				goto yy56;
			}
		}
yy97:
		++YYCURSOR;
		goto yy85;
yy98:
		yyaccept = 5;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '!') {
			if (yych <= '\n') {
				if (yych <= '\t') goto yy73;
				yyt2 = YYCURSOR;
				goto yy85;
			} else {
				if (yych == '\r') {
					yyt2 = YYCURSOR;
					goto yy85;
				}
				goto yy73;
			}
		} else {
			if (yych <= ';') {
				if (yych <= '"') goto yy84;
				if (yych <= ':') goto yy73;
				yyt2 = YYCURSOR;
				goto yy105;
			} else {
				if (yych == '\\') goto yy86;
				goto yy73;
			}
		}
yy99:
		yych = *++YYCURSOR;
yy100:
		if (yych <= 0x1F) {
			if (yych == '\t') goto yy99;
			goto yy90;
		} else {
			if (yych <= ' ') goto yy99;
			if (yych != ';') goto yy90;
		}
		++YYCURSOR;
		goto yy90;
yy102:
		yyaccept = 6;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= ' ') {
			if (yych <= '\n') {
				if (yych <= 0x08) goto yy76;
				if (yych <= '\t') {
					yyt4 = YYCURSOR;
					goto yy106;
				}
				yyt4 = YYCURSOR;
				goto yy90;
			} else {
				if (yych == '\r') {
					yyt4 = YYCURSOR;
					goto yy90;
				}
				if (yych <= 0x1F) goto yy76;
				yyt4 = YYCURSOR;
				goto yy106;
			}
		} else {
			if (yych <= ':') {
				if (yych == '"') goto yy89;
				goto yy76;
			} else {
				if (yych <= ';') {
					yyt4 = YYCURSOR;
					goto yy108;
				}
				if (yych == '\\') goto yy91;
				goto yy76;
			}
		}
yy103:
		yych = *++YYCURSOR;
		if (yych == '\t') goto yy109;
		if (yych == ' ') goto yy109;
		goto yy18;
yy104:
		yych = *++YYCURSOR;
		if (yych == 't') goto yy112;
		goto yy18;
yy105:
		yyaccept = 7;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '\r') {
			if (yych == '\n') goto yy85;
			if (yych <= '\f') goto yy73;
			goto yy85;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy73;
				goto yy84;
			} else {
				if (yych == '\\') goto yy86;
				goto yy73;
			}
		}
yy106:
		yyaccept = 8;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= ' ') {
			if (yych <= '\n') {
				if (yych <= 0x08) goto yy76;
				if (yych <= '\t') goto yy106;
				goto yy90;
			} else {
				if (yych == '\r') goto yy90;
				if (yych <= 0x1F) goto yy76;
				goto yy106;
			}
		} else {
			if (yych <= ':') {
				if (yych == '"') goto yy89;
				goto yy76;
			} else {
				if (yych <= ';') goto yy108;
				if (yych == '\\') goto yy91;
				goto yy76;
			}
		}
yy108:
		yyaccept = 8;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '\r') {
			if (yych == '\n') goto yy90;
			if (yych <= '\f') goto yy76;
			goto yy90;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy76;
				goto yy89;
			} else {
				if (yych == '\\') goto yy91;
				goto yy76;
			}
		}
yy109:
		yych = *++YYCURSOR;
		if (yych == '\t') goto yy109;
		if (yych == ' ') goto yy109;
		{ cond_res_i = 0; goto yyc_cond; }
yy112:
		yych = *++YYCURSOR;
		if (yych != 'i') goto yy18;
		yych = *++YYCURSOR;
		if (yych != 'o') goto yy18;
		yych = *++YYCURSOR;
		if (yych != 'n') goto yy18;
yy115:
		yych = *++YYCURSOR;
		if (yych <= 0x1F) {
			if (yych == '\t') goto yy115;
			goto yy18;
		} else {
			if (yych <= ' ') goto yy115;
			if (yych != ';') goto yy18;
		}
		++YYCURSOR;
		{ cond_res[0] = 1; cond_res_i = 0; goto yyc_init; }
	}
/* *********************************** */
yyc_cond:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  72,   0,  64,  64,   0,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 72,  64,   0,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			112, 112, 112, 112, 112, 112, 112, 112, 
			112, 112,  64,  64,  64,  64,  64,  64, 
			 64,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  64, 128,  64,  64,  96, 
			 64,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy123;
		}
		if (yych <= '(') {
			if (yych <= '\r') {
				if (yych <= 0x08) goto yy121;
				if (yych <= '\n') goto yy126;
				if (yych >= '\r') goto yy128;
			} else {
				if (yych <= 0x1F) goto yy121;
				if (yych <= '!') goto yy129;
				if (yych >= '(') goto yy131;
			}
		} else {
			if (yych <= 'Z') {
				if (yych <= '/') goto yy121;
				if (yych <= '9') {
					yyt1 = YYCURSOR;
					goto yy133;
				}
				if (yych >= 'A') {
					yyt1 = YYCURSOR;
					goto yy136;
				}
			} else {
				if (yych <= '_') {
					if (yych >= '_') {
						yyt1 = YYCURSOR;
						goto yy136;
					}
				} else {
					if (yych <= '`') goto yy121;
					if (yych <= 'z') {
						yyt1 = YYCURSOR;
						goto yy136;
					}
				}
			}
		}
yy121:
		++YYCURSOR;
yy122:
		{ cs_log_error("Syntax error in condition on line %d", lineno); goto out; }
yy123:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy123;
		}
		{ goto yyc_cond; }
yy126:
		++YYCURSOR;
		{ lineno++; goto yyc_cond; }
yy128:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy126;
		goto yy122;
yy129:
		++YYCURSOR;
		t1 = YYCURSOR - 1;
		{ sy_op_push(*t1); goto yyc_cond; }
yy131:
		++YYCURSOR;
		t1 = YYCURSOR - 1;
		{ sy_op_push(*t1); goto yyc_cond; }
yy133:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 16) {
			goto yy133;
		}
		t1 = yyt1;
		t2 = YYCURSOR;
		{ sy_res_push(atoi(t1));  goto yyc_cond_op; }
yy136:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy136;
		}
		if (yych == '(') goto yy139;
yy138:
		t1 = yyt1;
		t2 = YYCURSOR;
		{
      zend_string *tmp = zend_hash_str_find_ptr(&vars, t1, t2-t1);
      if (!tmp) {
        cs_log_error("unknown variable in condition on line %d", lineno);
        goto out;
      }
      sy_res_push(atoi(ZSTR_VAL(tmp)));
      goto yyc_cond_op;
    }
yy139:
		yych = *++YYCURSOR;
		if (yych == '"') {
			yyt2 = YYCURSOR;
			goto yy141;
		}
		if (yych == ')') {
			yyt2 = YYCURSOR;
			goto yy143;
		}
yy140:
		YYCURSOR = YYMARKER;
		if (yyaccept == 0) {
			goto yy138;
		} else {
			goto yy144;
		}
yy141:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy141;
		}
		if (yych <= '\r') goto yy140;
		if (yych <= '"') goto yy145;
		goto yy146;
yy143:
		++YYCURSOR;
yy144:
		t1 = yyt1;
		t3 = yyt2;
		t2 = yyt2 - 1;
		t4 = YYCURSOR - 1;
		{
      if (t4-t3 >= 2 && strlen("extension_loaded") == t2-t1 && strncmp("extension_loaded", t1, t2-t1) == 0) {
        int is_loaded = (zend_hash_str_find_ptr(&module_registry, t3+1, t4-t3-2) != NULL);
        sy_res_push(is_loaded);
      } else {
        cs_log_error("unknown function in condition on line %d", lineno);
        goto out;
      }
      goto yyc_cond_op;
    }
yy145:
		yych = *++YYCURSOR;
		if (yych == ')') goto yy143;
		goto yy140;
yy146:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy141;
		}
		if (yych <= '\r') goto yy140;
		if (yych >= '#') goto yy146;
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy146;
		}
		if (yych <= '\r') {
			if (yych == '\n') goto yy140;
			if (yych <= '\f') goto yy141;
			goto yy140;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy141;
				goto yy145;
			} else {
				if (yych != ')') goto yy141;
			}
		}
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy141;
		}
		if (yych <= '\r') goto yy144;
		if (yych <= '"') goto yy145;
		goto yy146;
	}
/* *********************************** */
yyc_cond_op:
	{
		static const unsigned char yybm[] = {
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0, 128,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			128,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
			  0,   0,   0,   0,   0,   0,   0,   0, 
		};
		yych = *YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy154;
		}
		if (yych <= ')') {
			if (yych <= '\r') {
				if (yych <= 0x08) goto yy152;
				if (yych <= '\n') goto yy157;
				if (yych >= '\r') goto yy159;
			} else {
				if (yych == '&') {
					yyt1 = YYCURSOR;
					goto yy160;
				}
				if (yych >= ')') goto yy161;
			}
		} else {
			if (yych <= '=') {
				if (yych <= ':') goto yy152;
				if (yych <= ';') goto yy163;
				if (yych <= '<') {
					yyt1 = YYCURSOR;
					goto yy165;
				}
				yyt1 = YYCURSOR;
				goto yy167;
			} else {
				if (yych <= '>') {
					yyt1 = YYCURSOR;
					goto yy165;
				}
				if (yych == '|') {
					yyt1 = YYCURSOR;
					goto yy168;
				}
			}
		}
yy152:
		++YYCURSOR;
yy153:
		{ cs_log_error("Syntax error in condition on line %d", lineno); goto out; }
yy154:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy154;
		}
		{ goto yyc_cond_op; }
yy157:
		++YYCURSOR;
		{ lineno++; goto yyc_cond_op; }
yy159:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy157;
		goto yy153;
yy160:
		yych = *++YYCURSOR;
		if (yych == '&') goto yy169;
		goto yy153;
yy161:
		++YYCURSOR;
		{
      while (cond_op_i && sy_op_peek() != '(') {
        SY_APPLY_OP_FROM_STACK();
      }
      if (cond_op_i == 0 || sy_op_peek() != '(') {
        cs_log_error("unbalanced parathesis on line %d", lineno); goto out;
      }
      cond_op_i--;
      goto yyc_cond_op;
    }
yy163:
		++YYCURSOR;
		{
      while (cond_op_i) {
        if (sy_op_peek() == '(') { cs_log_error("unbalanced parathesis on line %d", lineno); goto out; }
        SY_APPLY_OP_FROM_STACK();
      }
      if (cond_res_i > 1) { cs_log_error("invalid condition on line %d", lineno); goto out; }
      goto yyc_init;
    }
yy165:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy169;
yy166:
		t1 = yyt1;
		t2 = YYCURSOR;
		{
      char op1 = *t1;
      if (t2-t1 == 2) {
        switch (op1) {
          case '<': op1 = 'L'; break; // <=
          case '>': op1 = 'G'; break; // >=
        }
      }
      while (cond_op_i && sy_op_peek() != '(' && ((sy_op_precedence(sy_op_peek()) > sy_op_precedence(*t1)) || (sy_op_precedence(sy_op_peek()) == sy_op_precedence(*t1) && sy_op_is_left_assoc(*t1)))) {
        SY_APPLY_OP_FROM_STACK();
      }
      sy_op_push(*t1);
      goto yyc_cond;
    }
yy167:
		yych = *++YYCURSOR;
		if (yych == '=') goto yy169;
		goto yy153;
yy168:
		yych = *++YYCURSOR;
		if (yych != '|') goto yy153;
yy169:
		++YYCURSOR;
		goto yy166;
	}
/* *********************************** */
yyc_rule:
	{
		static const unsigned char yybm[] = {
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  88,  16,  64,  64,   0,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 88,  64,   0,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  64,  64,  64,  64,  64,  64, 
			 64,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  64, 128,  64,  64,  96, 
			 64,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  96,  96,  96,  96,  96, 
			 96,  96,  96,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
			 64,  64,  64,  64,  64,  64,  64,  64, 
		};
		yych = *YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy174;
		}
		if (yych <= '\r') {
			if (yych <= 0x08) goto yy172;
			if (yych <= '\n') goto yy177;
			if (yych >= '\r') goto yy178;
		} else {
			if (yych <= '.') {
				if (yych >= '.') goto yy179;
			} else {
				if (yych == ';') goto yy180;
			}
		}
yy172:
		++YYCURSOR;
yy173:
		{ goto end_of_rule; }
yy174:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 8) {
			goto yy174;
		}
		{  goto yyc_rule; }
yy177:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych <= '\r') {
			if (yych <= 0x08) goto yy173;
			if (yych <= '\n') {
				yyt1 = YYCURSOR;
				goto yy182;
			}
			if (yych <= '\f') goto yy173;
			yyt1 = YYCURSOR;
			goto yy185;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy173;
				yyt1 = YYCURSOR;
				goto yy182;
			} else {
				if (yych == '.') {
					yyt1 = YYCURSOR;
					goto yy186;
				}
				goto yy173;
			}
		}
yy178:
		yyaccept = 0;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yych == '\n') goto yy188;
		goto yy173;
yy179:
		yych = *++YYCURSOR;
		if (yych <= '^') {
			if (yych <= '@') goto yy173;
			if (yych <= 'Z') {
				yyt1 = YYCURSOR;
				goto yy189;
			}
			goto yy173;
		} else {
			if (yych == '`') goto yy173;
			if (yych <= 'z') {
				yyt1 = YYCURSOR;
				goto yy189;
			}
			goto yy173;
		}
yy180:
		++YYCURSOR;
		{
      end_of_rule:
      if (!cond_res[0]) { goto yyc_init; }
      parsed_rule[kw_i++] = (sp_parsed_keyword){0, 0, 0, 0, 0, 0};
      if (process_rule && process_rule(parsed_rule) != SUCCESS) {
        goto out;
      }
      goto yyc_init;
    }
yy182:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 16) {
			goto yy182;
		}
		if (yych == '\r') goto yy185;
		if (yych == '.') goto yy186;
yy184:
		YYCURSOR = YYMARKER;
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy173;
			} else {
				yyt3 = yyt4 = NULL;
				yyt2 = YYCURSOR;
				goto yy191;
			}
		} else {
			goto yy191;
		}
yy185:
		yych = *++YYCURSOR;
		if (yych == '\n') goto yy182;
		goto yy184;
yy186:
		++YYCURSOR;
		YYCURSOR = yyt1;
		{  lineno++; goto yyc_rule; }
yy188:
		yych = *++YYCURSOR;
		if (yych <= '\r') {
			if (yych <= 0x08) goto yy184;
			if (yych <= '\n') {
				yyt1 = YYCURSOR;
				goto yy182;
			}
			if (yych <= '\f') goto yy184;
			yyt1 = YYCURSOR;
			goto yy185;
		} else {
			if (yych <= ' ') {
				if (yych <= 0x1F) goto yy184;
				yyt1 = YYCURSOR;
				goto yy182;
			} else {
				if (yych == '.') {
					yyt1 = YYCURSOR;
					goto yy186;
				}
				goto yy184;
			}
		}
yy189:
		yyaccept = 1;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 32) {
			goto yy189;
		}
		if (yych == '(') {
			yyt2 = YYCURSOR;
			goto yy192;
		}
		yyt3 = yyt4 = NULL;
		yyt2 = YYCURSOR;
yy191:
		t1 = yyt1;
		t2 = yyt2;
		t3 = yyt3;
		t4 = yyt4;
		{
      if (!cond_res[0]) { goto yyc_rule; }
      if (kw_i == max_keywords) {
        cs_log_error("Too many keywords in rule (more than %d) on line %d", max_keywords, lineno);
        goto out;
      }
      sp_parsed_keyword kw = {.kw = (char*)t1, .kwlen = t2-t1, .arg = (char*)t3, .arglen = t4-t3, .argtype = SP_ARGTYPE_UNKNOWN, .lineno = lineno};
      if (t3 && t4) {
        if (t3 == t4) {
          kw.argtype = SP_ARGTYPE_EMPTY;
        } else if (t4-t3 >= 2 && *t3 == '"') {
          kw.arg = (char*)t3 + 1;
          kw.arglen = t4 - t3 - 2;
          kw.argtype = SP_ARGTYPE_STR;
        } else {
          zend_string *tmp = zend_hash_str_find_ptr(&vars, t3, t4-t3);
          if (!tmp) {
            cs_log_error("unknown variable on line %d", lineno);
            goto out;
          }
          kw.arg = ZSTR_VAL(tmp);
          kw.arglen = ZSTR_LEN(tmp);
          kw.argtype = SP_ARGTYPE_STR;
        }
      } else {
        kw.argtype = SP_ARGTYPE_NONE;
      }
      parsed_rule[kw_i++] = kw;
      goto yyc_rule;
    }
yy192:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= '"') {
				if (yych <= '!') goto yy184;
				yyt3 = YYCURSOR;
			} else {
				if (yych == ')') {
					yyt3 = yyt4 = YYCURSOR;
					goto yy195;
				}
				goto yy184;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') {
					yyt3 = YYCURSOR;
					goto yy196;
				}
				if (yych <= '^') goto yy184;
				yyt3 = YYCURSOR;
				goto yy196;
			} else {
				if (yych <= '`') goto yy184;
				if (yych <= 'z') {
					yyt3 = YYCURSOR;
					goto yy196;
				}
				goto yy184;
			}
		}
yy193:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy193;
		}
		if (yych <= '\r') goto yy184;
		if (yych <= '"') goto yy198;
		goto yy199;
yy195:
		++YYCURSOR;
		goto yy191;
yy196:
		yych = *++YYCURSOR;
		if (yych <= '@') {
			if (yych <= ')') {
				if (yych <= '(') goto yy184;
				yyt4 = YYCURSOR;
				goto yy195;
			} else {
				if (yych <= '/') goto yy184;
				if (yych <= '9') goto yy196;
				goto yy184;
			}
		} else {
			if (yych <= '_') {
				if (yych <= 'Z') goto yy196;
				if (yych <= '^') goto yy184;
				goto yy196;
			} else {
				if (yych <= '`') goto yy184;
				if (yych <= 'z') goto yy196;
				goto yy184;
			}
		}
yy198:
		yych = *++YYCURSOR;
		if (yych == ')') {
			yyt4 = YYCURSOR;
			goto yy195;
		}
		goto yy184;
yy199:
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 64) {
			goto yy193;
		}
		if (yych <= '\r') goto yy184;
		if (yych >= '#') goto yy199;
		yych = *++YYCURSOR;
		if (yybm[0+yych] & 128) {
			goto yy199;
		}
		if (yych <= '\r') {
			if (yych == '\n') goto yy184;
			if (yych <= '\f') goto yy193;
			goto yy184;
		} else {
			if (yych <= '"') {
				if (yych <= '!') goto yy193;
				goto yy198;
			} else {
				if (yych != ')') goto yy193;
				yyt4 = YYCURSOR;
			}
		}
		yyaccept = 2;
		yych = *(YYMARKER = ++YYCURSOR);
		if (yybm[0+yych] & 64) {
			goto yy193;
		}
		if (yych <= '\r') goto yy191;
		if (yych <= '"') goto yy198;
		goto yy199;
	}
}

out:
  zend_hash_destroy(&vars);
  return ret;
}