/* Generated by re2c */
#include "php_snuffleupagus.h"

#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"

enum YYCONDTYPE {
	yycinit,
	yyccond,
	yyccond_op,
	yycrule
};


#define cs_log_error(fmt, ...) sp_log_err("config", fmt, ##__VA_ARGS__)
#define cs_log_info(fmt, ...) sp_log_msg("config", SP_LOG_INFO, fmt, ##__VA_ARGS__)
#define cs_log_warning(fmt, ...) sp_log_warn("config", fmt, ##__VA_ARGS__)

#define MAX_CONDITIONS 100
#define MAX_KEYWORDS 16


zend_string *sp_get_arg_string(sp_parsed_keyword const *const kw) {
  if (!kw || !kw->arg) {
    return NULL;
  }

  zend_string *ret = zend_string_init(kw->arg, kw->arglen, 1);
  char *pin, *pout;
  pin = pout = ZSTR_VAL(ret);
  char const *const pend = pin + ZSTR_LEN(ret);

  while (pin < pend) {
    if (*pin == '\\') {
      pin++;
    }
    *pout = *pin;
    pin++; pout++;
  }

  if (pin != pout) {
    size_t len = pout - ZSTR_VAL(ret);
    ret = zend_string_truncate(ret, len, 1);
    ZSTR_VAL(ret)[len] = 0;
  }

  return ret;
}

zend_string *sp_get_textual_representation(sp_parsed_keyword const *const parsed_rule) {
  // a rule is "sp.keyword...keyword(arg);\0"
  size_t len = 3; // "sp" + ";"
  for (const sp_parsed_keyword *kw = parsed_rule; kw->kw; kw++) {
    len++; // .
    len += kw->kwlen;
    if (kw->argtype == SP_ARGTYPE_EMPTY) {
      len += 2; // ()
    } else if (kw->argtype == SP_ARGTYPE_STR) {
      len += 2; // ("
      len += kw->arglen;
      len += 2; // ")
    }
  }

  zend_string *ret = zend_string_alloc(len, 1);
  char *ptr = ZSTR_VAL(ret);

  memcpy(ptr, "sp", 2);
  ptr += 2;

  for (const sp_parsed_keyword *kw = parsed_rule; kw->kw; kw++) {
    *ptr++ = '.';

    memcpy(ptr, kw->kw, kw->kwlen);
    ptr += kw->kwlen;

    const bool has_parens = kw->argtype == SP_ARGTYPE_EMPTY ||
                            kw->argtype == SP_ARGTYPE_STR ||
                            kw->argtype == SP_ARGTYPE_UNKNOWN;

    if (has_parens) {
      *ptr++ = '(';
    }
    if (kw->argtype == SP_ARGTYPE_STR && kw->arg) {
      *ptr++ = '"';
      memcpy(ptr, kw->arg, kw->arglen);
      ptr += kw->arglen;
      *ptr++ = '"';
    }
    if (has_parens) {
      *ptr++ = ')';
    }
  }
  *ptr++ = ';';
  *ptr = 0;
  return ret;
}

static void str_dtor(zval *zv) {
  zend_string_release_ex(Z_STR_P(zv), 1);
}

// sy_ functions and macros are helpers for the shunting yard algorithm
#define sy_res_push(val) \
  if (cond_res_i >= MAX_CONDITIONS) { cs_log_error("condition too complex in %s:%zu", filename, lineno); goto out; } \
  cond_res[cond_res_i++] = val;
#define sy_res_pop() cond_res[--cond_res_i]
#define sy_op_push(op) \
  if (cond_op_i >= MAX_CONDITIONS) { cs_log_error("condition too complex in %s:%zu", filename, lineno); goto out; } \
  cond_op[cond_op_i++] = op;
#define sy_op_pop() cond_op[--cond_op_i]
#define sy_op_peek() cond_op[cond_op_i-1]

static inline int sy_op_precedence(const char op) {
  switch (op) {
    case '!': return 120;
    case '<':
    case '>':
    case 'L': // <=
    case 'G': // >=
              return 90;
    case '&': return 70;
    case '|': return 60;
    case '=': return 20;
  }
  return 0;
}

static inline int sy_op_is_left_assoc(const char op) {
  switch (op) {
    case '!': return 0;
  }
  return 1;
}

static int sy_apply_op(const char op, const int a, const int b) {
  switch (op) {
    case '!': return !a;
    case '&': return (b && a);
    case '|': return (b || a);
    case '<': return (b < a);
    case 'L': return (b <= a);
    case 'G': return (b >= a);
    case '>': return (b > a);
    case '=': return (b == a);
  }
  return 0;
}

#define SY_APPLY_OP_FROM_STACK() \
  char op = sy_op_pop(); \
  int unary = (op == '!'); \
  if (cond_res_i < (2 - unary)) { cs_log_error("not enough input in %s:%zu", filename, lineno); goto out; } \
  int a = sy_res_pop(); \
  int b = unary ? 0 : sy_res_pop(); \
  int res = sy_apply_op(op, a, b); \
  sy_res_push(res);

#define TMPSTR(tmpstr, t2, t1) \
      char tmpstr[1024]; \
      size_t tmplen = MIN(t2-t1-2, 1023); \
      strncpy(tmpstr, t1+1, tmplen); \
      tmpstr[tmplen] = 0;

// Non-ASCII bytes in a rule used to be silently dropped (a signed-char lexer
// mistook them for the NUL sentinel); reject them explicitly instead.
#define REJECT_NON_ASCII(start, end) \
  for (const char *nap = (start); nap < (end); nap++) { \
    if ((unsigned char)*nap >= 0x80) { \
      cs_log_error("non-ASCII character (0x%02X) in %s:%zu", \
                   (unsigned char)*nap, filename, lineno); \
      goto out; \
    } \
  }


zend_result sp_config_scan(const char *data, zend_result (*process_rule)(sp_parsed_keyword*), const char* filename)
{
  const char *YYMARKER, *t1, *t2, *t3, *t4;

  int ret = FAILURE;
  sp_parsed_keyword parsed_rule[MAX_KEYWORDS+1];
  int kw_i = 0;

  HashTable vars;
  zend_hash_init(&vars, 10, NULL, str_dtor, 1);
  zend_hash_str_add_ptr(&vars, ZEND_STRL("PHP_VERSION_ID"), zend_string_init(ZEND_STRL(ZEND_TOSTR(PHP_VERSION_ID)), 1));

  int cond_res[MAX_CONDITIONS] = {1};
  int cond_res_i = 0;
  char cond_op[MAX_CONDITIONS] = {0};
  int cond_op_i = 0;

  int cond = yycinit;
  size_t lineno = 1;

  const char *yyt1;
const char *yyt2;
const char *yyt3;
const char *yyt4;
const char *yyt5;

  
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	static const unsigned char yybm_init[] = {
		  0,  80,  80,  80,  80,  80,  80,  80, 
		 80,  88,   0,  80,  80,   0,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 88,  80,  16,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		112, 112, 112, 112, 112, 112, 112, 112, 
		112, 112,  80,  80,  80,  80,  80,  80, 
		 80, 112, 112, 112, 112, 112, 112, 112, 
		112, 112, 112, 112, 112, 112, 112, 112, 
		112, 112, 112, 112, 112, 112, 112, 112, 
		112, 112, 112,  80, 144,  80,  80, 112, 
		 80, 112, 112, 112, 112, 112, 112, 112, 
		112, 112, 112, 112, 112, 112, 112, 112, 
		112, 112, 112, 112, 112, 112, 112, 112, 
		112, 112, 112,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
		 80,  80,  80,  80,  80,  80,  80,  80, 
	};
	static const unsigned char yybm_cond[] = {
		  0,  64,  64,  64,  64,  64,  64,  64, 
		 64,  72,   0,  64,  64,   0,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 72,  64,   0,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		112, 112, 112, 112, 112, 112, 112, 112, 
		112, 112,  64,  64,  64,  64,  64,  64, 
		 64,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  64, 128,  64,  64,  96, 
		 64,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
	};
	static const unsigned char yybm_cond_op[] = {
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0, 128,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		128,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
		  0,   0,   0,   0,   0,   0,   0,   0, 
	};
	static const unsigned char yybm_rule[] = {
		  0,  64,  64,  64,  64,  64,  64,  64, 
		 64,  88,  16,  64,  64,   0,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 88,  64,   0,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  64,  64,  64,  64,  64,  64, 
		 64,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  64, 128,  64,  64,  96, 
		 64,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  96,  96,  96,  96,  96, 
		 96,  96,  96,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
		 64,  64,  64,  64,  64,  64,  64,  64, 
	};
	if (cond < 2) {
		if (cond < 1) {
			goto yyc_init;
		} else {
			goto yyc_cond;
		}
	} else {
		if (cond < 3) {
			goto yyc_cond_op;
		} else {
			goto yyc_rule;
		}
	}
/* *********************************** */
yyc_init:
	yych = *data;
	if (yybm_init[0+yych] & 8) {
		goto yy4;
	}
	if (yych <= '#') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy1;
			if (yych <= 0x08) goto yy2;
			goto yy5;
		} else {
			if (yych == '\r') goto yy6;
			if (yych <= '"') goto yy2;
			goto yy7;
		}
	} else {
		if (yych <= '@') {
			if (yych == ';') goto yy7;
			if (yych <= '?') goto yy2;
			goto yy8;
		} else {
			if (yych == 's') goto yy9;
			if (yych <= 0x7F) goto yy2;
			goto yy10;
		}
	}
yy1:
	++data;
	{ ret = SUCCESS; goto out; }
yy2:
	++data;
yy3:
	{ cs_log_error("parser error in %s:%zu", filename, lineno); goto out; }
yy4:
	yych = *++data;
	if (yybm_init[0+yych] & 8) {
		goto yy4;
	}
	{ goto yyc_init; }
yy5:
	++data;
	{ lineno++; goto yyc_init; }
yy6:
	yych = *++data;
	if (yych == '\n') goto yy5;
	goto yy3;
yy7:
	yych = *++data;
	if (yybm_init[0+yych] & 16) {
		goto yy7;
	}
	{ goto yyc_init; }
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++data);
	switch (yych) {
		case 'c': goto yy11;
		case 'e': goto yy13;
		case 'i': goto yy14;
		case 'l': goto yy15;
		case 's': goto yy16;
		case 'w': goto yy17;
		default: goto yy3;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++data);
	if (yych == 'e') goto yy18;
	if (yych == 'p') goto yy19;
	goto yy3;
yy10:
	++data;
	{ REJECT_NON_ASCII(data-1, data); }
yy11:
	yych = *++data;
	if (yych == 'o') goto yy20;
yy12:
	data = YYMARKER;
	if (yyaccept <= 2) {
		if (yyaccept <= 1) {
			if (yyaccept == 0) {
				goto yy3;
			} else {
				goto yy64;
			}
		} else {
			goto yy67;
		}
	} else {
		if (yyaccept == 3) {
			goto yy79;
		} else {
			goto yy83;
		}
	}
yy13:
	yych = *++data;
	if (yych == 'n') goto yy21;
	if (yych == 'r') goto yy22;
	goto yy12;
yy14:
	yych = *++data;
	if (yych == 'n') goto yy23;
	goto yy12;
yy15:
	yych = *++data;
	if (yych == 'o') goto yy24;
	goto yy12;
yy16:
	yych = *++data;
	if (yych == 'e') goto yy18;
	goto yy12;
yy17:
	yych = *++data;
	if (yych == 'a') goto yy25;
	goto yy12;
yy18:
	yych = *++data;
	if (yych == 't') goto yy26;
	goto yy12;
yy19:
	++data;
	{ kw_i = 0;  goto yyc_rule; }
yy20:
	yych = *++data;
	if (yych == 'n') goto yy27;
	goto yy12;
yy21:
	yych = *++data;
	if (yych == 'd') goto yy28;
	goto yy12;
yy22:
	yych = *++data;
	if (yych == 'r') goto yy29;
	goto yy12;
yy23:
	yych = *++data;
	if (yych == 'f') goto yy30;
	goto yy12;
yy24:
	yych = *++data;
	if (yych == 'g') goto yy31;
	goto yy12;
yy25:
	yych = *++data;
	if (yych == 'r') goto yy32;
	goto yy12;
yy26:
	yych = *++data;
	if (yych == '\t') goto yy33;
	if (yych == ' ') goto yy33;
	goto yy12;
yy27:
	yych = *++data;
	if (yych == 'd') goto yy34;
	goto yy12;
yy28:
	yych = *++data;
	if (yych == '_') goto yy35;
	goto yy12;
yy29:
	yych = *++data;
	if (yych == '"') goto yy12;
	if (yych == 'o') goto yy38;
	goto yy37;
yy30:
	yych = *++data;
	if (yych != 'o') goto yy12;
yy31:
	yych = *++data;
	if (yych == '"') goto yy12;
	goto yy40;
yy32:
	yych = *++data;
	if (yych == 'n') goto yy41;
	goto yy12;
yy33:
	yych = *++data;
	if (yych <= ' ') {
		if (yych == '\t') goto yy33;
		if (yych <= 0x1F) goto yy12;
		goto yy33;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy12;
			yyt1 = data;
			goto yy42;
		} else {
			if (yych <= '`') goto yy12;
			if (yych <= 'z') {
				yyt1 = data;
				goto yy42;
			}
			goto yy12;
		}
	}
yy34:
	yych = *++data;
	if (yych == 'i') goto yy43;
	goto yy12;
yy35:
	yych = *++data;
	if (yych == 'c') goto yy44;
	goto yy12;
yy36:
	yych = *++data;
yy37:
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy36;
		goto yy12;
	} else {
		if (yych <= ' ') goto yy36;
		if (yych == '"') {
			yyt1 = data;
			goto yy45;
		}
		goto yy12;
	}
yy38:
	yych = *++data;
	if (yych == 'r') goto yy46;
	goto yy12;
yy39:
	yych = *++data;
yy40:
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy39;
		goto yy12;
	} else {
		if (yych <= ' ') goto yy39;
		if (yych == '"') {
			yyt1 = data;
			goto yy47;
		}
		goto yy12;
	}
yy41:
	yych = *++data;
	if (yych == '"') goto yy12;
	if (yych == 'i') goto yy50;
	goto yy49;
yy42:
	yych = *++data;
	if (yybm_init[0+yych] & 32) {
		goto yy42;
	}
	if (yych == '\t') {
		yyt2 = data;
		goto yy51;
	}
	if (yych == ' ') {
		yyt2 = data;
		goto yy51;
	}
	goto yy12;
yy43:
	yych = *++data;
	if (yych == 't') goto yy52;
	goto yy12;
yy44:
	yych = *++data;
	if (yych == 'o') goto yy53;
	goto yy12;
yy45:
	yych = *++data;
	if (yybm_init[0+yych] & 64) {
		goto yy45;
	}
	if (yych <= '\r') goto yy12;
	if (yych <= '"') goto yy54;
	goto yy55;
yy46:
	yych = *++data;
	if (yych == '"') goto yy12;
	goto yy37;
yy47:
	yych = *++data;
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			goto yy47;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych <= '\f') goto yy47;
			goto yy12;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy47;
			goto yy56;
		} else {
			if (yych == '\\') goto yy57;
			goto yy47;
		}
	}
yy48:
	yych = *++data;
yy49:
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy48;
		goto yy12;
	} else {
		if (yych <= ' ') goto yy48;
		if (yych == '"') {
			yyt1 = data;
			goto yy58;
		}
		goto yy12;
	}
yy50:
	yych = *++data;
	if (yych == 'n') goto yy59;
	goto yy12;
yy51:
	yych = *++data;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy51;
		goto yy12;
	} else {
		if (yych <= ' ') goto yy51;
		if (yych == '"') {
			yyt3 = data;
			goto yy60;
		}
		goto yy12;
	}
yy52:
	yych = *++data;
	if (yych == 'i') goto yy61;
	goto yy12;
yy53:
	yych = *++data;
	if (yych == 'n') goto yy62;
	goto yy12;
yy54:
	yych = *++data;
	if (yych == ';') goto yy63;
	goto yy12;
yy55:
	yych = *++data;
	if (yybm_init[0+yych] & 64) {
		goto yy45;
	}
	if (yych <= '\r') goto yy12;
	if (yych <= '"') goto yy65;
	goto yy55;
yy56:
	yych = *++data;
	if (yych == ';') goto yy66;
	goto yy12;
yy57:
	yych = *++data;
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			goto yy47;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych <= '\f') goto yy47;
			goto yy12;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy47;
			goto yy68;
		} else {
			if (yych == '\\') goto yy57;
			goto yy47;
		}
	}
yy58:
	yych = *++data;
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			goto yy58;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych <= '\f') goto yy58;
			goto yy12;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy58;
			goto yy69;
		} else {
			if (yych == '\\') goto yy70;
			goto yy58;
		}
	}
yy59:
	yych = *++data;
	if (yych == 'g') goto yy71;
	goto yy12;
yy60:
	yych = *++data;
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			goto yy60;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych <= '\f') goto yy60;
			goto yy12;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy60;
			goto yy72;
		} else {
			if (yych == '\\') goto yy73;
			goto yy60;
		}
	}
yy61:
	yych = *++data;
	if (yych == 'o') goto yy74;
	goto yy12;
yy62:
	yych = *++data;
	if (yych == 'd') goto yy75;
	goto yy12;
yy63:
	++data;
yy64:
	t1 = yyt1;
	t2 = data - 1;
	{
      if (!cond_res[0]) { goto yyc_init; }
      TMPSTR(tmpstr, t2, t1);
      cs_log_error("[%s:%zu]: %s", filename, lineno, tmpstr);
      goto out;
    }
yy65:
	yych = *++data;
	if (yybm_init[0+yych] & 128) {
		goto yy55;
	}
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			goto yy45;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych <= '\f') goto yy45;
			goto yy12;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy45;
			goto yy54;
		} else {
			if (yych == ';') goto yy76;
			goto yy45;
		}
	}
yy66:
	++data;
yy67:
	t1 = yyt1;
	t2 = data - 1;
	{
      if (!cond_res[0]) { goto yyc_init; }
      TMPSTR(tmpstr, t2, t1);
      cs_log_info("[%s:%zu]: %s", filename, lineno, tmpstr);
      goto yyc_init;
    }
yy68:
	yych = *++data;
	if (yych <= '!') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy12;
			if (yych <= '\t') goto yy47;
			goto yy12;
		} else {
			if (yych == '\r') goto yy12;
			goto yy47;
		}
	} else {
		if (yych <= ';') {
			if (yych <= '"') goto yy56;
			if (yych <= ':') goto yy47;
			goto yy77;
		} else {
			if (yych == '\\') goto yy57;
			goto yy47;
		}
	}
yy69:
	yych = *++data;
	if (yych == ';') goto yy78;
	goto yy12;
yy70:
	yych = *++data;
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			goto yy58;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych <= '\f') goto yy58;
			goto yy12;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy58;
			goto yy80;
		} else {
			if (yych == '\\') goto yy70;
			goto yy58;
		}
	}
yy71:
	yych = *++data;
	if (yych == '"') goto yy12;
	goto yy49;
yy72:
	yych = *++data;
	if (yych <= 0x1F) {
		if (yych == '\t') {
			yyt5 = data;
			goto yy81;
		}
		goto yy12;
	} else {
		if (yych <= ' ') {
			yyt5 = data;
			goto yy81;
		}
		if (yych == ';') {
			yyt5 = data;
			goto yy82;
		}
		goto yy12;
	}
yy73:
	yych = *++data;
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			goto yy60;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych <= '\f') goto yy60;
			goto yy12;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy60;
			goto yy84;
		} else {
			if (yych == '\\') goto yy73;
			goto yy60;
		}
	}
yy74:
	yych = *++data;
	if (yych == 'n') goto yy85;
	goto yy12;
yy75:
	yych = *++data;
	if (yych == 'i') goto yy86;
	goto yy12;
yy76:
	yyaccept = 1;
	yych = *(YYMARKER = ++data);
	if (yybm_init[0+yych] & 64) {
		goto yy45;
	}
	if (yych <= '\r') goto yy64;
	if (yych <= '"') goto yy54;
	goto yy55;
yy77:
	yyaccept = 2;
	yych = *(YYMARKER = ++data);
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy67;
			goto yy47;
		} else {
			if (yych <= '\n') goto yy67;
			if (yych <= '\f') goto yy47;
			goto yy67;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy47;
			goto yy56;
		} else {
			if (yych == '\\') goto yy57;
			goto yy47;
		}
	}
yy78:
	++data;
yy79:
	t1 = yyt1;
	t2 = data - 1;
	{
      if (!cond_res[0]) { goto yyc_init; }
      TMPSTR(tmpstr, t2, t1);
      cs_log_warning("[%s:%zu]: %s", filename, lineno, tmpstr);
      goto yyc_init;
    }
yy80:
	yych = *++data;
	if (yych <= '!') {
		if (yych <= '\n') {
			if (yych <= 0x00) goto yy12;
			if (yych <= '\t') goto yy58;
			goto yy12;
		} else {
			if (yych == '\r') goto yy12;
			goto yy58;
		}
	} else {
		if (yych <= ';') {
			if (yych <= '"') goto yy69;
			if (yych <= ':') goto yy58;
			goto yy87;
		} else {
			if (yych == '\\') goto yy70;
			goto yy58;
		}
	}
yy81:
	yych = *++data;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy81;
		goto yy12;
	} else {
		if (yych <= ' ') goto yy81;
		if (yych != ';') goto yy12;
	}
yy82:
	++data;
	yyt4 = yyt5;
yy83:
	t1 = yyt1;
	t2 = yyt2;
	t3 = yyt3;
	t4 = yyt4;
	{
      if (!cond_res[0]) { goto yyc_init; }
      const char *key = t1;
      size_t keylen = t2 - t1;
      zend_string *tmp = zend_hash_str_find_ptr(&vars, key, keylen);
      if (tmp) {
        zend_hash_str_del(&vars, key, keylen);
      }
      tmp = zend_string_init(t3+1, t4-t3-2, 1);  // `-2` for the surrounding double quotes.
      zend_hash_str_add_ptr(&vars, key, keylen, tmp);
      goto yyc_init;
    }
yy84:
	yych = *++data;
	if (yych <= 0x1F) {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			if (yych <= 0x08) goto yy60;
			yyt5 = data;
			goto yy88;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych == '\r') goto yy12;
			goto yy60;
		}
	} else {
		if (yych <= ':') {
			if (yych <= ' ') {
				yyt5 = data;
				goto yy88;
			}
			if (yych == '"') goto yy72;
			goto yy60;
		} else {
			if (yych <= ';') {
				yyt5 = data;
				goto yy89;
			}
			if (yych == '\\') goto yy73;
			goto yy60;
		}
	}
yy85:
	yych = *++data;
	if (yych == '\t') goto yy90;
	if (yych == ' ') goto yy90;
	goto yy12;
yy86:
	yych = *++data;
	if (yych == 't') goto yy91;
	goto yy12;
yy87:
	yyaccept = 3;
	yych = *(YYMARKER = ++data);
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy79;
			goto yy58;
		} else {
			if (yych <= '\n') goto yy79;
			if (yych <= '\f') goto yy58;
			goto yy79;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy58;
			goto yy69;
		} else {
			if (yych == '\\') goto yy70;
			goto yy58;
		}
	}
yy88:
	yych = *++data;
	if (yych <= 0x1F) {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy12;
			if (yych <= 0x08) goto yy60;
			goto yy88;
		} else {
			if (yych <= '\n') goto yy12;
			if (yych == '\r') goto yy12;
			goto yy60;
		}
	} else {
		if (yych <= ':') {
			if (yych <= ' ') goto yy88;
			if (yych == '"') goto yy72;
			goto yy60;
		} else {
			if (yych <= ';') goto yy89;
			if (yych == '\\') goto yy73;
			goto yy60;
		}
	}
yy89:
	yyaccept = 4;
	yych = *(YYMARKER = ++data);
	yyt4 = yyt5;
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy83;
			goto yy60;
		} else {
			if (yych <= '\n') goto yy83;
			if (yych <= '\f') goto yy60;
			goto yy83;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy60;
			goto yy72;
		} else {
			if (yych == '\\') goto yy73;
			goto yy60;
		}
	}
yy90:
	yych = *++data;
	if (yych == '\t') goto yy90;
	if (yych == ' ') goto yy90;
	{ cond_res_i = 0; goto yyc_cond; }
yy91:
	yych = *++data;
	if (yych != 'i') goto yy12;
	yych = *++data;
	if (yych != 'o') goto yy12;
	yych = *++data;
	if (yych != 'n') goto yy12;
yy92:
	yych = *++data;
	if (yych <= 0x1F) {
		if (yych == '\t') goto yy92;
		goto yy12;
	} else {
		if (yych <= ' ') goto yy92;
		if (yych != ';') goto yy12;
	}
	++data;
	{ cond_res[0] = 1; cond_res_i = 0; goto yyc_init; }
/* *********************************** */
yyc_cond:
	yych = *data;
	if (yybm_cond[0+yych] & 8) {
		goto yy96;
	}
	if (yych <= '\'') {
		if (yych <= '\f') {
			if (yych <= 0x08) goto yy94;
			if (yych <= '\n') goto yy97;
		} else {
			if (yych <= '\r') goto yy98;
			if (yych <= 0x1F) goto yy94;
			if (yych <= '!') goto yy99;
		}
	} else {
		if (yych <= '@') {
			if (yych <= '(') goto yy100;
			if (yych <= '/') goto yy94;
			if (yych <= '9') {
				yyt1 = data;
				goto yy101;
			}
		} else {
			if (yych <= 'Z') {
				yyt1 = data;
				goto yy102;
			}
			if (yych <= '`') goto yy94;
			if (yych <= 'z') {
				yyt1 = data;
				goto yy102;
			}
		}
	}
yy94:
	++data;
yy95:
	{ cs_log_error("syntax error in condition in %s:%zu", filename, lineno); goto out; }
yy96:
	yych = *++data;
	if (yybm_cond[0+yych] & 8) {
		goto yy96;
	}
	{ goto yyc_cond; }
yy97:
	++data;
	{ lineno++; goto yyc_cond; }
yy98:
	yych = *++data;
	if (yych == '\n') goto yy97;
	goto yy95;
yy99:
	++data;
	t1 = data - 1;
	{ sy_op_push(*t1); goto yyc_cond; }
yy100:
	++data;
	t1 = data - 1;
	{ sy_op_push(*t1); goto yyc_cond; }
yy101:
	yych = *++data;
	if (yybm_cond[0+yych] & 16) {
		goto yy101;
	}
	t1 = yyt1;
	t2 = data;
	{ sy_res_push(atoi(t1));  goto yyc_cond_op; }
yy102:
	yyaccept = 0;
	yych = *(YYMARKER = ++data);
	if (yybm_cond[0+yych] & 32) {
		goto yy102;
	}
	if (yych == '(') goto yy104;
yy103:
	t1 = yyt1;
	t2 = data;
	{
      zend_string *tmp = zend_hash_str_find_ptr(&vars, t1, t2-t1);
      if (!tmp) {
        cs_log_error("unknown variable in condition in %s:%zu", filename, lineno);
        goto out;
      }
      sy_res_push(atoi(ZSTR_VAL(tmp)));
      goto yyc_cond_op;
    }
yy104:
	yych = *++data;
	if (yych == '"') {
		yyt2 = data;
		goto yy106;
	}
	if (yych == ')') {
		yyt2 = data;
		goto yy107;
	}
yy105:
	data = YYMARKER;
	if (yyaccept == 0) {
		goto yy103;
	} else {
		goto yy108;
	}
yy106:
	yych = *++data;
	if (yybm_cond[0+yych] & 64) {
		goto yy106;
	}
	if (yych <= '\r') goto yy105;
	if (yych <= '"') goto yy109;
	goto yy110;
yy107:
	++data;
yy108:
	t1 = yyt1;
	t3 = yyt2;
	t2 = yyt2 - 1;
	t4 = data - 1;
	{
      if (t4-t3 >= 2 && strlen("extension_loaded") == t2-t1 && strncmp("extension_loaded", t1, t2-t1) == 0) {
        int is_loaded = (zend_hash_str_find_ptr(&module_registry, t3+1, t4-t3-2) != NULL);
        sy_res_push(is_loaded);
      } else {
        cs_log_error("unknown function in condition in %s:%zu", filename, lineno);
        goto out;
      }
      goto yyc_cond_op;
    }
yy109:
	yych = *++data;
	if (yych == ')') goto yy107;
	goto yy105;
yy110:
	yych = *++data;
	if (yybm_cond[0+yych] & 64) {
		goto yy106;
	}
	if (yych <= '\r') goto yy105;
	if (yych >= '#') goto yy110;
	yych = *++data;
	if (yybm_cond[0+yych] & 128) {
		goto yy110;
	}
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy105;
			goto yy106;
		} else {
			if (yych <= '\n') goto yy105;
			if (yych <= '\f') goto yy106;
			goto yy105;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy106;
			goto yy109;
		} else {
			if (yych != ')') goto yy106;
		}
	}
	yyaccept = 1;
	yych = *(YYMARKER = ++data);
	if (yybm_cond[0+yych] & 64) {
		goto yy106;
	}
	if (yych <= '\r') goto yy108;
	if (yych <= '"') goto yy109;
	goto yy110;
/* *********************************** */
yyc_cond_op:
	yych = *data;
	if (yybm_cond_op[0+yych] & 128) {
		goto yy114;
	}
	if (yych <= ')') {
		if (yych <= '\r') {
			if (yych <= 0x08) goto yy112;
			if (yych <= '\n') goto yy115;
			if (yych >= '\r') goto yy116;
		} else {
			if (yych == '&') {
				yyt1 = data;
				goto yy117;
			}
			if (yych >= ')') goto yy118;
		}
	} else {
		if (yych <= '=') {
			if (yych <= ':') goto yy112;
			if (yych <= ';') goto yy119;
			if (yych <= '<') {
				yyt1 = data;
				goto yy120;
			}
			yyt1 = data;
			goto yy122;
		} else {
			if (yych <= '>') {
				yyt1 = data;
				goto yy120;
			}
			if (yych == '|') {
				yyt1 = data;
				goto yy123;
			}
		}
	}
yy112:
	++data;
yy113:
	{ cs_log_error("syntax error in condition in %s:%zu", filename, lineno); goto out; }
yy114:
	yych = *++data;
	if (yybm_cond_op[0+yych] & 128) {
		goto yy114;
	}
	{ goto yyc_cond_op; }
yy115:
	++data;
	{ lineno++; goto yyc_cond_op; }
yy116:
	yych = *++data;
	if (yych == '\n') goto yy115;
	goto yy113;
yy117:
	yych = *++data;
	if (yych == '&') goto yy124;
	goto yy113;
yy118:
	++data;
	{
      while (cond_op_i && sy_op_peek() != '(') {
        SY_APPLY_OP_FROM_STACK();
      }
      if (cond_op_i == 0 || sy_op_peek() != '(') {
        cs_log_error("unbalanced parenthesis in %s:%zu", filename, lineno); goto out;
      }
      cond_op_i--;
      goto yyc_cond_op;
    }
yy119:
	++data;
	{
      while (cond_op_i) {
        if (sy_op_peek() == '(') { cs_log_error("unbalanced parenthesis in %s:%zu", filename, lineno); goto out; }
        SY_APPLY_OP_FROM_STACK();
      }
      if (cond_res_i > 1) { cs_log_error("invalid condition in %s:%zu", filename, lineno); goto out; }
      goto yyc_init;
    }
yy120:
	yych = *++data;
	if (yych == '=') goto yy124;
yy121:
	t1 = yyt1;
	t2 = data;
	{
      char op1 = *t1;
      if (t2-t1 == 2) {
        switch (op1) {
          case '<': op1 = 'L'; break; // <=
          case '>': op1 = 'G'; break; // >=
        }
      }
      const int cur_prec = sy_op_precedence(op1);
      while (cond_op_i && sy_op_peek() != '(') {
        const int top_prec = sy_op_precedence(sy_op_peek());
        if (top_prec < cur_prec ||
            (top_prec == cur_prec && !sy_op_is_left_assoc(op1))) {
          break;
        }
        SY_APPLY_OP_FROM_STACK();
      }
      sy_op_push(op1);
      goto yyc_cond;
    }
yy122:
	yych = *++data;
	if (yych == '=') goto yy124;
	goto yy113;
yy123:
	yych = *++data;
	if (yych != '|') goto yy113;
yy124:
	++data;
	goto yy121;
/* *********************************** */
yyc_rule:
	yych = *data;
	if (yybm_rule[0+yych] & 8) {
		goto yy127;
	}
	if (yych <= '-') {
		if (yych <= '\n') {
			if (yych >= '\t') goto yy128;
		} else {
			if (yych == '\r') goto yy129;
		}
	} else {
		if (yych <= ':') {
			if (yych <= '.') goto yy130;
		} else {
			if (yych <= ';') goto yy131;
			if (yych >= 0x80) goto yy132;
		}
	}
	++data;
yy126:
	{ goto end_of_rule; }
yy127:
	yych = *++data;
	if (yybm_rule[0+yych] & 8) {
		goto yy127;
	}
	{  goto yyc_rule; }
yy128:
	yyaccept = 0;
	yych = *(YYMARKER = ++data);
	if (yych <= '\r') {
		if (yych <= 0x08) goto yy126;
		if (yych <= '\n') {
			yyt1 = data;
			goto yy133;
		}
		if (yych <= '\f') goto yy126;
		yyt1 = data;
		goto yy135;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy126;
			yyt1 = data;
			goto yy133;
		} else {
			if (yych == '.') {
				yyt1 = data;
				goto yy136;
			}
			goto yy126;
		}
	}
yy129:
	yyaccept = 0;
	yych = *(YYMARKER = ++data);
	if (yych == '\n') goto yy137;
	goto yy126;
yy130:
	yych = *++data;
	if (yych <= '@') goto yy126;
	if (yych <= 'Z') {
		yyt1 = data;
		goto yy138;
	}
	if (yych <= '`') goto yy126;
	if (yych <= 'z') {
		yyt1 = data;
		goto yy138;
	}
	goto yy126;
yy131:
	++data;
	{
      end_of_rule:
      if (!cond_res[0]) { goto yyc_init; }
      parsed_rule[kw_i++] = (sp_parsed_keyword){0, 0, 0, 0, 0, 0, NULL};
      if (process_rule && process_rule(parsed_rule) != SUCCESS) {
        goto out;
      }
      goto yyc_init;
    }
yy132:
	++data;
	{ REJECT_NON_ASCII(data-1, data); }
yy133:
	yych = *++data;
	if (yybm_rule[0+yych] & 16) {
		goto yy133;
	}
	if (yych == '\r') goto yy135;
	if (yych == '.') goto yy136;
yy134:
	data = YYMARKER;
	if (yyaccept <= 1) {
		if (yyaccept == 0) {
			goto yy126;
		} else {
			yyt3 = yyt4 = NULL;
			yyt2 = data;
			goto yy139;
		}
	} else {
		goto yy139;
	}
yy135:
	yych = *++data;
	if (yych == '\n') goto yy133;
	goto yy134;
yy136:
	++data;
	data = yyt1;
	{  lineno++; goto yyc_rule; }
yy137:
	yych = *++data;
	if (yych <= '\r') {
		if (yych <= 0x08) goto yy134;
		if (yych <= '\n') {
			yyt1 = data;
			goto yy133;
		}
		if (yych <= '\f') goto yy134;
		yyt1 = data;
		goto yy135;
	} else {
		if (yych <= ' ') {
			if (yych <= 0x1F) goto yy134;
			yyt1 = data;
			goto yy133;
		} else {
			if (yych == '.') {
				yyt1 = data;
				goto yy136;
			}
			goto yy134;
		}
	}
yy138:
	yyaccept = 1;
	yych = *(YYMARKER = ++data);
	if (yybm_rule[0+yych] & 32) {
		goto yy138;
	}
	if (yych == '(') {
		yyt2 = data;
		goto yy140;
	}
	yyt3 = yyt4 = NULL;
	yyt2 = data;
yy139:
	t1 = yyt1;
	t2 = yyt2;
	t3 = yyt3;
	t4 = yyt4;
	{
      if (!cond_res[0]) { goto yyc_rule; }
      if (kw_i == MAX_KEYWORDS) {
        cs_log_error("too many keywords in rule (more than %d) in %s:%zu", MAX_KEYWORDS, filename, lineno);
        goto out;
      }
      sp_parsed_keyword kw = {
        .kw = t1,
	.kwlen = t2-t1,
	.arg = t3,
	.arglen = t4-t3,
	.argtype = SP_ARGTYPE_UNKNOWN,
	.lineno = lineno,
	.filename = filename
      };
      if (t3 && t4) {
        REJECT_NON_ASCII(t3, t4);
        if (t3 == t4) {
          kw.argtype = SP_ARGTYPE_EMPTY;
        } else if (t4-t3 >= 2 && *t3 == '"') {
          kw.arg = t3 + 1;
          kw.arglen = t4 - t3 - 2;
          kw.argtype = SP_ARGTYPE_STR;
        } else {
          zend_string *tmp = zend_hash_str_find_ptr(&vars, t3, t4-t3);
          if (!tmp) {
            cs_log_error("unknown variable in %s:%zu", filename, lineno);
            goto out;
          }
          kw.arg = ZSTR_VAL(tmp);
          kw.arglen = ZSTR_LEN(tmp);
          kw.argtype = SP_ARGTYPE_STR;
        }
      } else {
        kw.argtype = SP_ARGTYPE_NONE;
      }
      parsed_rule[kw_i++] = kw;
      goto yyc_rule;
    }
yy140:
	yych = *++data;
	if (yych <= ')') {
		if (yych == '"') {
			yyt3 = data;
			goto yy141;
		}
		if (yych <= '(') goto yy134;
		yyt3 = yyt4 = data;
		goto yy142;
	} else {
		if (yych <= 'Z') {
			if (yych <= '@') goto yy134;
			yyt3 = data;
			goto yy143;
		} else {
			if (yych <= '`') goto yy134;
			if (yych <= 'z') {
				yyt3 = data;
				goto yy143;
			}
			goto yy134;
		}
	}
yy141:
	yych = *++data;
	if (yybm_rule[0+yych] & 64) {
		goto yy141;
	}
	if (yych <= '\r') goto yy134;
	if (yych <= '"') goto yy144;
	goto yy145;
yy142:
	++data;
	goto yy139;
yy143:
	yych = *++data;
	if (yych <= '@') {
		if (yych <= ')') {
			if (yych <= '(') goto yy134;
			yyt4 = data;
			goto yy142;
		} else {
			if (yych <= '/') goto yy134;
			if (yych <= '9') goto yy143;
			goto yy134;
		}
	} else {
		if (yych <= '_') {
			if (yych <= 'Z') goto yy143;
			if (yych <= '^') goto yy134;
			goto yy143;
		} else {
			if (yych <= '`') goto yy134;
			if (yych <= 'z') goto yy143;
			goto yy134;
		}
	}
yy144:
	yych = *++data;
	if (yych == ')') {
		yyt4 = data;
		goto yy142;
	}
	goto yy134;
yy145:
	yych = *++data;
	if (yybm_rule[0+yych] & 64) {
		goto yy141;
	}
	if (yych <= '\r') goto yy134;
	if (yych >= '#') goto yy145;
	yych = *++data;
	if (yybm_rule[0+yych] & 128) {
		goto yy145;
	}
	if (yych <= '\r') {
		if (yych <= '\t') {
			if (yych <= 0x00) goto yy134;
			goto yy141;
		} else {
			if (yych <= '\n') goto yy134;
			if (yych <= '\f') goto yy141;
			goto yy134;
		}
	} else {
		if (yych <= '"') {
			if (yych <= '!') goto yy141;
			goto yy144;
		} else {
			if (yych != ')') goto yy141;
			yyt4 = data;
		}
	}
	yyaccept = 2;
	yych = *(YYMARKER = ++data);
	if (yybm_rule[0+yych] & 64) {
		goto yy141;
	}
	if (yych <= '\r') goto yy139;
	if (yych <= '"') goto yy144;
	goto yy145;
}

out:
  zend_hash_destroy(&vars);
  return ret;
}
